/* automatically generated from xfdesktop-settings-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\"?>\n<!--Generated with glade3 3.4.5 on Sun Nov 16 "
  "16:39:43 2008 -->\n<interface>\n  <object class=\"GtkAdjustment\" id=\""
  "adjustment3\">\n    <property name=\"upper\">192</property>\n    <prope"
  "rty name=\"lower\">8</property>\n    <property name=\"page_increment\">"
  "10</property>\n    <property name=\"step_increment\">1</property>\n    "
  "<property name=\"page_size\">0</property>\n    <property name=\"value\""
  ">48</property>\n  </object>\n  <object class=\"GtkAdjustment\" id=\"adj"
  "ustment4\">\n    <property name=\"upper\">144</property>\n    <property"
  " name=\"lower\">0</property>\n    <property name=\"page_increment\">10<"
  "/property>\n    <property name=\"step_increment\">1</property>\n    <pr"
  "operty name=\"page_size\">0</property>\n    <property name=\"value\">12"
  "</property>\n  </object>\n  <object class=\"GtkAdjustment\" id=\"adjust"
  "ment_tooltip\">\n    <property name=\"upper\">256</property>\n    <prop"
  "erty name=\"lower\">0</property>\n    <property name=\"page_increment\""
  ">10</property>\n    <property name=\"step_increment\">1</property>\n   "
  " <property name=\"page_size\">0</property>\n    <property name=\"value\""
  ">128</property>\n  </object>\n  <object class=\"GtkListStore\" id=\"mod"
  "el3\">\n    <columns>\n      <column type=\"gchararray\"/>\n    </colum"
  "ns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Left</col>\n      </row>\n      <row>\n        <col id=\"0\" translata"
  "ble=\"yes\">Middle</col>\n      </row>\n      <row>\n        <col id=\""
  "0\" translatable=\"yes\">Right</col>\n      </row>\n    </data>\n  </ob"
  "ject>\n  <object class=\"GtkListStore\" id=\"model4\">\n    <columns>\n"
  "      <column type=\"gchararray\"/>\n    </columns>\n    <data>\n      "
  "<row>\n        <col id=\"0\" translatable=\"yes\">None</col>\n      </r"
  "ow>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Shift</col"
  ">\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Alt</col>\n      </row>\n      <row>\n        <col id=\"0\" translatab"
  "le=\"yes\">Control</col>\n      </row>\n    </data>\n  </object>\n  <ob"
  "ject class=\"GtkListStore\" id=\"model5\">\n    <columns>\n      <colum"
  "n type=\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n     "
  "   <col id=\"0\" translatable=\"yes\">Left</col>\n      </row>\n      <"
  "row>\n        <col id=\"0\" translatable=\"yes\">Middle</col>\n      </"
  "row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Right</co"
  "l>\n      </row>\n    </data>\n  </object>\n  <object class=\"GtkListSt"
  "ore\" id=\"model6\">\n    <columns>\n      <column type=\"gchararray\"/"
  ">\n    </columns>\n    <data>\n      <row>\n        <col id=\"0\" trans"
  "latable=\"yes\">None</col>\n      </row>\n      <row>\n        <col id="
  "\"0\" translatable=\"yes\">Shift</col>\n      </row>\n      <row>\n    "
  "    <col id=\"0\" translatable=\"yes\">Alt</col>\n      </row>\n      <"
  "row>\n        <col id=\"0\" translatable=\"yes\">Control</col>\n      <"
  "/row>\n    </data>\n  </object>\n  <object class=\"GtkListStore\" id=\""
  "model7\">\n    <columns>\n      <column type=\"gchararray\"/>\n    </co"
  "lumns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\"y"
  "es\">None</col>\n      </row>\n      <row>\n        <col id=\"0\" trans"
  "latable=\"yes\">Minimized application icons</col>\n      </row>\n      "
  "<row>\n        <col id=\"0\" translatable=\"yes\">File/launcher icons</"
  "col>\n      </row>\n    </data>\n  </object>\n  <object class=\"XfceTit"
  "ledDialog\" id=\"prefs_dialog\">\n    <property name=\"events\">GDK_POI"
  "NTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK"
  " | GDK_BUTTON_RELEASE_MASK</property>\n    <property name=\"title\" tra"
  "nslatable=\"yes\">Desktop</property>\n    <property name=\"window_posit"
  "ion\">GTK_WIN_POS_CENTER_ON_PARENT</property>\n    <property name=\"ico"
  "n_name\">preferences-desktop-wallpaper</property>\n    <property name=\""
  "type_hint\">GDK_WINDOW_TYPE_HINT_DIALOG</property>\n    <property name="
  "\"has_separator\">False</property>\n    <property name=\"subtitle\" tra"
  "nslatable=\"yes\">Set desktop background and menu and icon behavior</pr"
  "operty>\n    <property name=\"default-width\">640</property>\n    <prop"
  "erty name=\"default-height\">480</property>\n    <child internal-child="
  "\"vbox\">\n      <object class=\"GtkVBox\" id=\"dialog-vbox1\">\n      "
  "  <property name=\"visible\">True</property>\n        <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        <propert"
  "y name=\"spacing\">2</property>\n        <child>\n          <object cla"
  "ss=\"GtkAlignment\" id=\"alignment1\">\n            <property name=\"vi"
  "sible\">True</property>\n            <child>\n              <object cla"
  "ss=\"GtkNotebook\" id=\"notebook_settings\">\n                <property"
  " name=\"visible\">True</property>\n                <property name=\"can"
  "_focus\">True</property>\n                <property name=\"events\">GDK"
  "_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_"
  "MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <property na"
  "me=\"border_width\">6</property>\n                <child>\n            "
  "      <object class=\"GtkNotebook\" id=\"notebook_screens\">\n         "
  "           <property name=\"visible\">True</property>\n                "
  "    <property name=\"can_focus\">True</property>\n                    <"
  "property name=\"show-border\">False</property>\n                  </obj"
  "ect>\n                </child>\n                <child type=\"tab\">\n "
  "                 <object class=\"GtkLabel\" id=\"label1\">\n           "
  "         <property name=\"visible\">True</property>\n                  "
  "  <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTIO"
  "N_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property"
  ">\n                    <property name=\"label\" translatable=\"yes\">_B"
  "ackground</property>\n                    <property name=\"use_underlin"
  "e\">True</property>\n                  </object>\n                  <pa"
  "cking>\n                    <property name=\"tab_fill\">False</property"
  ">\n                  </packing>\n                </child>\n            "
  "    <child>\n                  <object class=\"GtkVBox\" id=\"vbox4\">\n"
  "                    <property name=\"visible\">True</property>\n       "
  "             <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_PO"
  "INTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MAS"
  "K</property>\n                    <property name=\"border_width\">12</p"
  "roperty>\n                    <property name=\"spacing\">6</property>\n"
  "                    <child>\n                      <object class=\"GtkF"
  "rame\" id=\"frame4\">\n                        <property name=\"visible"
  "\">True</property>\n                        <property name=\"events\">G"
  "DK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRES"
  "S_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        <p"
  "roperty name=\"label_xalign\">0</property>\n                        <pr"
  "operty name=\"shadow_type\">GTK_SHADOW_NONE</property>\n               "
  "         <child>\n                          <object class=\"GtkAlignmen"
  "t\" id=\"alignment5\">\n                            <property name=\"vi"
  "sible\">True</property>\n                            <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "           <property name=\"border_width\">6</property>\n              "
  "              <property name=\"left_padding\">6</property>\n           "
  "                 <child>\n                              <object class=\""
  "GtkVBox\" id=\"vbox7\">\n                                <property name"
  "=\"visible\">True</property>\n                                <property"
  " name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK"
  " | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        "
  "                        <property name=\"spacing\">6</property>\n      "
  "                          <child>\n                                  <o"
  "bject class=\"GtkCheckButton\" id=\"chk_show_desktop_menu\">\n         "
  "                           <property name=\"visible\">True</property>\n"
  "                                    <property name=\"can_focus\">True</"
  "property>\n                                    <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "            <property name=\"label\" translatable=\"yes\">Include appli"
  "cations menu on _desktop right click</property>\n                      "
  "              <property name=\"use_underline\">True</property>\n       "
  "                             <property name=\"active\">True</property>\n"
  "                                    <property name=\"draw_indicator\">T"
  "rue</property>\n                                  </object>\n          "
  "                      </child>\n                                <child>"
  "\n                                  <object class=\"GtkAlignment\" id=\""
  "box_menu_subopts\">\n                                    <property name"
  "=\"visible\">True</property>\n                                    <prop"
  "erty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_"
  "MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n    "
  "                                <property name=\"bottom_padding\">6</pr"
  "operty>\n                                    <property name=\"left_padd"
  "ing\">12</property>\n                                    <child>\n     "
  "                                 <object class=\"GtkVBox\" id=\"vbox10\""
  ">\n                                        <property name=\"visible\">T"
  "rue</property>\n                                        <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              "
  "                          <property name=\"spacing\">6</property>\n    "
  "                                    <child>\n                          "
  "                <object class=\"GtkHBox\" id=\"hbox11\">\n             "
  "                               <property name=\"events\">GDK_POINTER_MO"
  "TION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_"
  "BUTTON_RELEASE_MASK</property>\n                                       "
  "     <property name=\"spacing\">12</property>\n                        "
  "                    <child>\n                                          "
  "    <object class=\"GtkLabel\" id=\"label17\">\n                       "
  "                         <property name=\"visible\">True</property>\n  "
  "                                              <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "                        <property name=\"label\" translatable=\"yes\">_"
  "Button:</property>\n                                                <pr"
  "operty name=\"use_underline\">True</property>\n                        "
  "                        <property name=\"mnemonic_widget\">combobox1</p"
  "roperty>\n                                              </object>\n    "
  "                                          <packing>\n                  "
  "                              <property name=\"expand\">False</property"
  ">\n                                              </packing>\n          "
  "                                  </child>\n                           "
  "                 <child>\n                                             "
  " <object class=\"GtkComboBox\" id=\"combobox1\">\n                     "
  "                           <property name=\"visible\">True</property>\n"
  "                                                <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "                          <property name=\"model\">model3</property>\n "
  "                                               <child>\n               "
  "                                   <object class=\"GtkCellRendererText\""
  " id=\"renderer3\"/>\n                                                  "
  "<attributes>\n                                                    <attr"
  "ibute name=\"text\">0</attribute>\n                                    "
  "              </attributes>\n                                          "
  "      </child>\n                                              </object>"
  "\n                                              <packing>\n            "
  "                                    <property name=\"expand\">False</pr"
  "operty>\n                                                <property name"
  "=\"position\">1</property>\n                                           "
  "   </packing>\n                                            </child>\n  "
  "                                          <child>\n                    "
  "                          <object class=\"GtkLabel\" id=\"label18\">\n "
  "                                               <property name=\"visible"
  "\">True</property>\n                                                <pr"
  "operty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HIN"
  "T_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n  "
  "                                              <property name=\"label\" "
  "translatable=\"yes\">Mo_difier:</property>\n                           "
  "                     <property name=\"use_underline\">True</property>\n"
  "                                                <property name=\"mnemon"
  "ic_widget\">combobox2</property>\n                                     "
  "         </object>\n                                              <pack"
  "ing>\n                                                <property name=\""
  "expand\">False</property>\n                                            "
  "    <property name=\"position\">2</property>\n                         "
  "                     </packing>\n                                      "
  "      </child>\n                                            <child>\n  "
  "                                            <object class=\"GtkComboBox"
  "\" id=\"combobox2\">\n                                                <"
  "property name=\"visible\">True</property>\n                            "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                                                <p"
  "roperty name=\"model\">model4</property>\n                             "
  "                   <child>\n                                           "
  "       <object class=\"GtkCellRendererText\" id=\"renderer4\"/>\n      "
  "                                            <attributes>\n             "
  "                                       <attribute name=\"text\">0</attr"
  "ibute>\n                                                  </attributes>"
  "\n                                                </child>\n           "
  "                                   </object>\n                         "
  "                     <packing>\n                                       "
  "         <property name=\"expand\">False</property>\n                  "
  "                              <property name=\"position\">3</property>\n"
  "                                              </packing>\n             "
  "                               </child>\n                              "
  "            </object>\n                                        </child>"
  "\n                                        <child>\n                    "
  "                      <object class=\"GtkCheckButton\" id=\"chk_menu_sh"
  "ow_app_icons\">\n                                            <property "
  "name=\"visible\">True</property>\n                                     "
  "       <property name=\"can_focus\">True</property>\n                  "
  "                          <property name=\"events\">GDK_POINTER_MOTION_"
  "MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTO"
  "N_RELEASE_MASK</property>\n                                            "
  "<property name=\"label\" translatable=\"yes\">Show _application icons i"
  "n menu</property>\n                                            <propert"
  "y name=\"use_underline\">True</property>\n                             "
  "               <property name=\"active\">True</property>\n             "
  "                               <property name=\"draw_indicator\">True</"
  "property>\n                                          </object>\n       "
  "                                   <packing>\n                         "
  "                   <property name=\"position\">1</property>\n          "
  "                                </packing>\n                           "
  "             </child>\n                                        <child>\n"
  "                                          <object class=\"GtkHBox\" id="
  "\"hbox12\">\n                                            <property name"
  "=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GD"
  "K_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n             "
  "                               <property name=\"spacing\">12</property>"
  "\n                                            <child>\n                "
  "                              <object class=\"GtkButton\" id=\"button5\""
  ">\n                                                <property name=\"vis"
  "ible\">True</property>\n                                               "
  " <property name=\"can_focus\">True</property>\n                        "
  "                        <property name=\"receives_default\">True</prope"
  "rty>\n                                                <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                                <property name=\"label\" translatable=\""
  "yes\">_Edit desktop menu</property>\n                                  "
  "              <property name=\"use_underline\">True</property>\n       "
  "                                       </object>\n                     "
  "                         <packing>\n                                   "
  "             <property name=\"expand\">False</property>\n              "
  "                                </packing>\n                           "
  "                 </child>\n                                          </"
  "object>\n                                          <packing>\n         "
  "                                   <property name=\"position\">2</prope"
  "rty>\n                                          </packing>\n           "
  "                             </child>\n                                "
  "      </object>\n                                    </child>\n        "
  "                          </object>\n                                  "
  "<packing>\n                                    <property name=\"positio"
  "n\">1</property>\n                                  </packing>\n       "
  "                         </child>\n                              </obje"
  "ct>\n                            </child>\n                          </"
  "object>\n                        </child>\n                        <chi"
  "ld type=\"label\">\n                          <object class=\"GtkLabel\""
  " id=\"label10\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "    <property name=\"label\" translatable=\"yes\">&lt;b&gt;Desktop Menu"
  "&lt;/b&gt;</property>\n                            <property name=\"use"
  "_markup\">True</property>\n                          </object>\n       "
  "                 </child>\n                      </object>\n           "
  "           <packing>\n                        <property name=\"expand\""
  ">False</property>\n                      </packing>\n                  "
  "  </child>\n                    <child>\n                      <object "
  "class=\"GtkFrame\" id=\"frame5\">\n                        <property na"
  "me=\"visible\">True</property>\n                        <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              "
  "          <property name=\"label_xalign\">0</property>\n               "
  "         <property name=\"shadow_type\">GTK_SHADOW_NONE</property>\n   "
  "                     <child>\n                          <object class=\""
  "GtkAlignment\" id=\"alignment6\">\n                            <propert"
  "y name=\"visible\">True</property>\n                            <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "                      <property name=\"border_width\">6</property>\n   "
  "                         <property name=\"left_padding\">6</property>\n"
  "                            <child>\n                              <obj"
  "ect class=\"GtkVBox\" id=\"vbox8\">\n                                <p"
  "roperty name=\"visible\">True</property>\n                             "
  "   <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTI"
  "ON_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</propert"
  "y>\n                                <property name=\"spacing\">6</prope"
  "rty>\n                                <child>\n                        "
  "          <object class=\"GtkCheckButton\" id=\"chk_show_winlist_menu\""
  ">\n                                    <property name=\"visible\">True<"
  "/property>\n                                    <property name=\"can_fo"
  "cus\">True</property>\n                                    <property na"
  "me=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | "
  "GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n           "
  "                         <property name=\"label\" translatable=\"yes\">"
  "Show _window list menu on desktop middle click</property>\n            "
  "                        <property name=\"use_underline\">True</property"
  ">\n                                    <property name=\"active\">True</"
  "property>\n                                    <property name=\"draw_in"
  "dicator\">True</property>\n                                  </object>\n"
  "                                </child>\n                             "
  "   <child>\n                                  <object class=\"GtkAlignm"
  "ent\" id=\"box_winlist_subopts\">\n                                    "
  "<property name=\"visible\">True</property>\n                           "
  "         <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTE"
  "R_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</p"
  "roperty>\n                                    <property name=\"bottom_p"
  "adding\">6</property>\n                                    <property na"
  "me=\"left_padding\">12</property>\n                                    "
  "<child>\n                                      <object class=\"GtkVBox\""
  " id=\"vbox11\">\n                                        <property name"
  "=\"visible\">True</property>\n                                        <"
  "property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_H"
  "INT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                                        <property name=\"spacing\">6</p"
  "roperty>\n                                        <child>\n            "
  "                              <object class=\"GtkHBox\" id=\"hbox14\">\n"
  "                                            <property name=\"events\">G"
  "DK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRES"
  "S_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                          "
  "                  <property name=\"spacing\">12</property>\n           "
  "                                 <child>\n                             "
  "                 <object class=\"GtkLabel\" id=\"label23\">\n          "
  "                                      <property name=\"visible\">True</"
  "property>\n                                                <property na"
  "me=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | "
  "GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n           "
  "                                     <property name=\"label\" translata"
  "ble=\"yes\">B_utton:</property>\n                                      "
  "          <property name=\"use_underline\">True</property>\n           "
  "                                     <property name=\"mnemonic_widget\""
  ">combobox8</property>\n                                              </"
  "object>\n                                              <packing>\n     "
  "                                           <property name=\"expand\">Fa"
  "lse</property>\n                                              </packing"
  ">\n                                            </child>\n              "
  "                              <child>\n                                "
  "              <object class=\"GtkComboBox\" id=\"combobox8\">\n        "
  "                                        <property name=\"visible\">True"
  "</property>\n                                                <property "
  "name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK "
  "| GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n         "
  "                                       <property name=\"model\">model5<"
  "/property>\n                                                <child>\n  "
  "                                                <object class=\"GtkCell"
  "RendererText\" id=\"renderer5\"/>\n                                    "
  "              <attributes>\n                                           "
  "         <attribute name=\"text\">0</attribute>\n                      "
  "                            </attributes>\n                            "
  "                    </child>\n                                         "
  "     </object>\n                                              <packing>"
  "\n                                                <property name=\"expa"
  "nd\">False</property>\n                                                "
  "<property name=\"position\">1</property>\n                             "
  "                 </packing>\n                                          "
  "  </child>\n                                            <child>\n      "
  "                                        <object class=\"GtkLabel\" id=\""
  "label24\">\n                                                <property n"
  "ame=\"visible\">True</property>\n                                      "
  "          <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINT"
  "ER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</"
  "property>\n                                                <property na"
  "me=\"label\" translatable=\"yes\">Modi_fier:</property>\n              "
  "                                  <property name=\"use_underline\">True"
  "</property>\n                                                <property "
  "name=\"mnemonic_widget\">combobox9</property>\n                        "
  "                      </object>\n                                      "
  "        <packing>\n                                                <pro"
  "perty name=\"expand\">False</property>\n                               "
  "                 <property name=\"position\">2</property>\n            "
  "                                  </packing>\n                         "
  "                   </child>\n                                          "
  "  <child>\n                                              <object class="
  "\"GtkComboBox\" id=\"combobox9\">\n                                    "
  "            <property name=\"visible\">True</property>\n               "
  "                                 <property name=\"events\">GDK_POINTER_"
  "MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GD"
  "K_BUTTON_RELEASE_MASK</property>\n                                     "
  "           <property name=\"model\">model6</property>\n                "
  "                                <child>\n                              "
  "                    <object class=\"GtkCellRendererText\" id=\"renderer"
  "6\"/>\n                                                  <attributes>\n"
  "                                                    <attribute name=\"t"
  "ext\">0</attribute>\n                                                  "
  "</attributes>\n                                                </child>"
  "\n                                              </object>\n            "
  "                                  <packing>\n                          "
  "                      <property name=\"expand\">False</property>\n     "
  "                                           <property name=\"position\">"
  "3</property>\n                                              </packing>\n"
  "                                            </child>\n                 "
  "                         </object>\n                                   "
  "     </child>\n                                        <child>\n       "
  "                                   <object class=\"GtkCheckButton\" id="
  "\"chk_winlist_show_app_icons\">\n                                      "
  "      <property name=\"visible\">True</property>\n                     "
  "                       <property name=\"can_focus\">True</property>\n  "
  "                                          <property name=\"events\">GDK"
  "_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_"
  "MASK | GDK_BUTTON_RELEASE_MASK</property>\n                            "
  "                <property name=\"label\" translatable=\"yes\">Sh_ow app"
  "lication icons in menu</property>\n                                    "
  "        <property name=\"use_underline\">True</property>\n             "
  "                               <property name=\"active\">True</property"
  ">\n                                            <property name=\"draw_in"
  "dicator\">True</property>\n                                          </"
  "object>\n                                          <packing>\n         "
  "                                   <property name=\"position\">1</prope"
  "rty>\n                                          </packing>\n           "
  "                             </child>\n                                "
  "        <child>\n                                          <object clas"
  "s=\"GtkCheckButton\" id=\"chk_show_winlist_ws_names\">\n               "
  "                             <property name=\"visible\">True</property>"
  "\n                                            <property name=\"can_focu"
  "s\">True</property>\n                                            <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n     "
  "                                       <property name=\"label\" transla"
  "table=\"yes\">Show workspace _names in list</property>\n               "
  "                             <property name=\"use_underline\">True</pro"
  "perty>\n                                            <property name=\"ac"
  "tive\">True</property>\n                                            <pr"
  "operty name=\"draw_indicator\">True</property>\n                       "
  "                   </object>\n                                         "
  " <packing>\n                                            <property name="
  "\"position\">2</property>\n                                          </"
  "packing>\n                                        </child>\n           "
  "                             <child>\n                                 "
  "         <object class=\"GtkAlignment\" id=\"box_winlist_names_subopts\""
  ">\n                                            <property name=\"visible"
  "\">True</property>\n                                            <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "                                      <property name=\"left_padding\">1"
  "2</property>\n                                            <child>\n    "
  "                                          <object class=\"GtkCheckButto"
  "n\" id=\"chk_show_winlist_ws_submenus\">\n                             "
  "                   <property name=\"visible\">True</property>\n        "
  "                                        <property name=\"can_focus\">Tr"
  "ue</property>\n                                                <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "                                         <property name=\"label\" trans"
  "latable=\"yes\">Use _submenus for the windows in each workspace</proper"
  "ty>\n                                                <property name=\"u"
  "se_underline\">True</property>\n                                       "
  "         <property name=\"draw_indicator\">True</property>\n           "
  "                                   </object>\n                         "
  "                   </child>\n                                          "
  "</object>\n                                          <packing>\n       "
  "                                     <property name=\"position\">3</pro"
  "perty>\n                                          </packing>\n         "
  "                               </child>\n                              "
  "          <child>\n                                          <object cl"
  "ass=\"GtkCheckButton\" id=\"chk_show_winlist_sticky_once\">\n          "
  "                                  <property name=\"visible\">True</prop"
  "erty>\n                                            <property name=\"can"
  "_focus\">True</property>\n                                            <"
  "property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_H"
  "INT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                                            <property name=\"label\" tr"
  "anslatable=\"yes\">Show s_ticky windows only in active workspace</prope"
  "rty>\n                                            <property name=\"use_"
  "underline\">True</property>\n                                          "
  "  <property name=\"draw_indicator\">True</property>\n                  "
  "                        </object>\n                                    "
  "      <packing>\n                                            <property "
  "name=\"position\">4</property>\n                                       "
  "   </packing>\n                                        </child>\n      "
  "                                  <child>\n                            "
  "              <object class=\"GtkCheckButton\" id=\"chk_show_app_remove"
  "_workspaces\">\n                                            <property n"
  "ame=\"visible\">True</property>\n                                      "
  "      <property name=\"can_focus\">True</property>\n                   "
  "                         <property name=\"events\">GDK_POINTER_MOTION_M"
  "ASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON"
  "_RELEASE_MASK</property>\n                                            <"
  "property name=\"label\" translatable=\"yes\">Show a_dd and remove works"
  "pace options in list</property>\n                                      "
  "      <property name=\"active\">True</property>\n                      "
  "                      <property name=\"use_underline\">True</property>\n"
  "                                            <property name=\"draw_indic"
  "ator\">True</property>\n                                          </obj"
  "ect>\n                                          <packing>\n            "
  "                                <property name=\"position\">5</property"
  ">\n                                          </packing>\n              "
  "                          </child>\n                                   "
  "   </object>\n                                    </child>\n           "
  "                       </object>\n                                  <pa"
  "cking>\n                                    <property name=\"position\""
  ">1</property>\n                                  </packing>\n          "
  "                      </child>\n                              </object>"
  "\n                            </child>\n                          </obj"
  "ect>\n                        </child>\n                        <child "
  "type=\"label\">\n                          <object class=\"GtkLabel\" i"
  "d=\"label11\">\n                            <property name=\"visible\">"
  "True</property>\n                            <property name=\"events\">"
  "GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRE"
  "SS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                         "
  "   <property name=\"label\" translatable=\"yes\">&lt;b&gt;Window List M"
  "enu&lt;/b&gt;</property>\n                            <property name=\""
  "use_markup\">True</property>\n                          </object>\n    "
  "                    </child>\n                      </object>\n        "
  "              <packing>\n                        <property name=\"expan"
  "d\">False</property>\n                        <property name=\"position"
  "\">1</property>\n                      </packing>\n                    "
  "</child>\n                  </object>\n                </child>\n      "
  "          <child type=\"tab\">\n                  <object class=\"GtkLa"
  "bel\" id=\"label2\">\n                    <property name=\"visible\">Tr"
  "ue</property>\n                    <property name=\"events\">GDK_POINTE"
  "R_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | "
  "GDK_BUTTON_RELEASE_MASK</property>\n                    <property name="
  "\"label\" translatable=\"yes\">_Menus</property>\n                    <"
  "property name=\"use_underline\">True</property>\n                  </ob"
  "ject>\n                  <packing>\n                    <property name="
  "\"position\">1</property>\n                    <property name=\"tab_fil"
  "l\">False</property>\n                  </packing>\n                </c"
  "hild>\n                <child>\n                  <object class=\"GtkVB"
  "ox\" id=\"vbox9\">\n                    <property name=\"visible\">True"
  "</property>\n                    <property name=\"events\">GDK_POINTER_"
  "MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GD"
  "K_BUTTON_RELEASE_MASK</property>\n                    <property name=\""
  "border_width\">12</property>\n                    <property name=\"spac"
  "ing\">6</property>\n                    <child>\n                      "
  "<object class=\"GtkFrame\" id=\"frame6\">\n                        <pro"
  "perty name=\"visible\">True</property>\n                        <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "                  <property name=\"label_xalign\">0</property>\n       "
  "                 <property name=\"shadow_type\">GTK_SHADOW_NONE</proper"
  "ty>\n                        <child>\n                          <object"
  " class=\"GtkAlignment\" id=\"alignment11\">\n                          "
  "  <property name=\"visible\">True</property>\n                         "
  "   <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTI"
  "ON_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</propert"
  "y>\n                            <property name=\"border_width\">6</prop"
  "erty>\n                            <property name=\"left_padding\">6</p"
  "roperty>\n                            <child>\n                        "
  "      <object class=\"GtkVBox\" id=\"vbox6\">\n                        "
  "        <property name=\"visible\">True</property>\n                   "
  "             <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_PO"
  "INTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MAS"
  "K</property>\n                                <property name=\"spacing\""
  ">6</property>\n                                <child>\n               "
  "                   <object class=\"GtkHBox\" id=\"hbox7\">\n           "
  "                         <property name=\"visible\">True</property>\n  "
  "                                  <property name=\"events\">GDK_POINTER"
  "_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | G"
  "DK_BUTTON_RELEASE_MASK</property>\n                                    "
  "<property name=\"spacing\">12</property>\n                             "
  "       <child>\n                                      <object class=\"G"
  "tkLabel\" id=\"label12\">\n                                        <pro"
  "perty name=\"visible\">True</property>\n                               "
  "         <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTE"
  "R_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</p"
  "roperty>\n                                        <property name=\"labe"
  "l\" translatable=\"yes\">Icon _type:</property>\n                      "
  "                  <property name=\"use_underline\">True</property>\n   "
  "                                   </object>\n                         "
  "             <packing>\n                                        <proper"
  "ty name=\"expand\">False</property>\n                                  "
  "    </packing>\n                                    </child>\n         "
  "                           <child>\n                                   "
  "   <object class=\"GtkComboBox\" id=\"combo_icons\">\n                 "
  "                       <property name=\"visible\">True</property>\n    "
  "                                    <property name=\"events\">GDK_POINT"
  "ER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK |"
  " GDK_BUTTON_RELEASE_MASK</property>\n                                  "
  "      <property name=\"model\">model7</property>\n                     "
  "                   <child>\n                                          <"
  "object class=\"GtkCellRendererText\" id=\"renderer7\"/>\n              "
  "                            <attributes>\n                             "
  "               <attribute name=\"text\">0</attribute>\n                "
  "                          </attributes>\n                              "
  "          </child>\n                                      </object>\n  "
  "                                    <packing>\n                        "
  "                <property name=\"expand\">False</property>\n           "
  "                             <property name=\"position\">1</property>\n"
  "                                      </packing>\n                     "
  "               </child>\n                                  </object>\n "
  "                                 <packing>\n                           "
  "         <property name=\"expand\">False</property>\n                  "
  "                </packing>\n                                </child>\n "
  "                               <child>\n                               "
  "   <object class=\"GtkHBox\" id=\"hbox8\">\n                           "
  "         <property name=\"visible\">True</property>\n                  "
  "                  <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n                                    <property name=\""
  "spacing\">12</property>\n                                    <child>\n "
  "                                     <object class=\"GtkLabel\" id=\"la"
  "bel13\">\n                                        <property name=\"visi"
  "ble\">True</property>\n                                        <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "                                 <property name=\"label\" translatable="
  "\"yes\">Icon _size:</property>\n                                       "
  " <property name=\"use_underline\">True</property>\n                    "
  "                  </object>\n                                      <pac"
  "king>\n                                        <property name=\"expand\""
  ">False</property>\n                                      </packing>\n  "
  "                                  </child>\n                           "
  "         <child>\n                                      <object class=\""
  "GtkSpinButton\" id=\"spin_icon_size\">\n                               "
  "         <property name=\"visible\">True</property>\n                  "
  "                      <property name=\"can_focus\">True</property>\n   "
  "                                     <property name=\"events\">GDK_POIN"
  "TER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK "
  "| GDK_BUTTON_RELEASE_MASK</property>\n                                 "
  "       <property name=\"adjustment\">adjustment3</property>\n          "
  "                            </object>\n                                "
  "      <packing>\n                                        <property name"
  "=\"expand\">False</property>\n                                        <"
  "property name=\"position\">1</property>\n                              "
  "        </packing>\n                                    </child>\n     "
  "                             </object>\n                               "
  "   <packing>\n                                    <property name=\"expa"
  "nd\">False</property>\n                                    <property na"
  "me=\"position\">1</property>\n                                  </packi"
  "ng>\n                                </child>\n                        "
  "        <child>\n                                  <object class=\"GtkC"
  "heckButton\" id=\"chk_show_thumbnails\">\n                             "
  "       <property name=\"visible\">True</property>\n                    "
  "                <property name=\"can_focus\">True</property>\n         "
  "                           <property name=\"events\">GDK_POINTER_MOTION"
  "_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTT"
  "ON_RELEASE_MASK</property>\n                                    <proper"
  "ty name=\"label\" translatable=\"yes\">Show t_humbnails</property>\n   "
  "                                 <property name=\"tooltip-text\" transl"
  "atable=\"yes\">Select this option to display preview-able files on the "
  "desktop as automatically generated thumbnail icons.</property>\n       "
  "                             <property name=\"use_underline\">True</pro"
  "perty>\n                                    <property name=\"draw_indic"
  "ator\">True</property>\n                                  </object>\n  "
  "                              </child>\n                               "
  " <child>\n                                  <object class=\"GtkCheckBut"
  "ton\" id=\"chk_show_hidden_files\">\n                                  "
  "  <property name=\"visible\">True</property>\n                         "
  "           <property name=\"can_focus\">True</property>\n              "
  "                      <property name=\"events\">GDK_POINTER_MOTION_MASK"
  " | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RE"
  "LEASE_MASK</property>\n                                    <property na"
  "me=\"label\" translatable=\"yes\">Show hidden files on the desktop</pro"
  "perty>\n                                    <property name=\"use_underl"
  "ine\">True</property>\n                                    <property na"
  "me=\"draw_indicator\">True</property>\n                                "
  "  </object>\n                                </child>\n                "
  "                <child>\n                                  <object clas"
  "s=\"GtkCheckButton\" id=\"chk_single_click\">\n                        "
  "            <property name=\"visible\">True</property>\n               "
  "                     <property name=\"can_focus\">True</property>\n    "
  "                                <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                                    <p"
  "roperty name=\"label\" translatable=\"yes\">Single _click to activate i"
  "tems</property>\n                                    <property name=\"u"
  "se_underline\">True</property>\n                                    <pr"
  "operty name=\"draw_indicator\">True</property>\n                       "
  "           </object>\n                                </child>\n       "
  "                         <child>\n                                  <ob"
  "ject class=\"GtkHBox\" id=\"hboxtooltip\">\n                           "
  "         <property name=\"visible\">True</property>\n                  "
  "                  <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n                                    <property name=\""
  "spacing\">4</property>\n                                    <child>\n  "
  "                                    <object class=\"GtkCheckButton\" id"
  "=\"chk_show_tooltips\">\n                                        <prope"
  "rty name=\"visible\">True</property>\n                                 "
  "       <property name=\"can_focus\">True</property>\n                  "
  "                      <property name=\"events\">GDK_POINTER_MOTION_MASK"
  " | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RE"
  "LEASE_MASK</property>\n                                        <propert"
  "y name=\"label\" translatable=\"yes\">Show icon tooltips. Size:</proper"
  "ty>\n                                        <property name=\"use_under"
  "line\">True</property>\n                                        <proper"
  "ty name=\"draw_indicator\">True</property>\n                           "
  "             <property name=\"active\">True</property>\n               "
  "                       </object>\n                                     "
  " <packing>\n                                        <property name=\"ex"
  "pand\">False</property>\n                                      </packin"
  "g>\n                                    </child>\n                     "
  "               <child>\n                                      <object c"
  "lass=\"GtkSpinButton\" id=\"spin_tooltip_size\">\n                     "
  "                   <property name=\"visible\">True</property>\n        "
  "                                <property name=\"sensitive\">True</prop"
  "erty>\n                                        <property name=\"can_foc"
  "us\">True</property>\n                                        <property"
  " name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK"
  " | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        "
  "                                <property name=\"adjustment\">adjustmen"
  "t_tooltip</property>\n                                        <property"
  " name=\"tooltip-text\" translatable=\"yes\">Size of the tooltip preview"
  " image.</property>\n                                      </object>\n  "
  "                                    <packing>\n                        "
  "                <property name=\"expand\">False</property>\n           "
  "                             <property name=\"position\">1</property>\n"
  "                                      </packing>\n                     "
  "               </child>\n                                  </object>\n "
  "                                 <packing>\n                           "
  "         <property name=\"expand\">False</property>\n                  "
  "                  <property name=\"position\">2</property>\n           "
  "                       </packing>\n                                </ch"
  "ild>\n                                <child>\n                        "
  "          <object class=\"GtkHBox\" id=\"hbox9\">\n                    "
  "                <property name=\"visible\">True</property>\n           "
  "                         <property name=\"events\">GDK_POINTER_MOTION_M"
  "ASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON"
  "_RELEASE_MASK</property>\n                                    <property"
  " name=\"spacing\">4</property>\n                                    <ch"
  "ild>\n                                      <object class=\"GtkCheckBut"
  "ton\" id=\"chk_custom_font_size\">\n                                   "
  "     <property name=\"visible\">True</property>\n                      "
  "                  <property name=\"can_focus\">True</property>\n       "
  "                                 <property name=\"events\">GDK_POINTER_"
  "MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GD"
  "K_BUTTON_RELEASE_MASK</property>\n                                     "
  "   <property name=\"label\" translatable=\"yes\">Use custom _font size:"
  "</property>\n                                        <property name=\"u"
  "se_underline\">True</property>\n                                       "
  " <property name=\"draw_indicator\">True</property>\n                   "
  "                   </object>\n                                      <pa"
  "cking>\n                                        <property name=\"expand"
  "\">False</property>\n                                      </packing>\n"
  "                                    </child>\n                         "
  "           <child>\n                                      <object class"
  "=\"GtkSpinButton\" id=\"spin_font_size\">\n                            "
  "            <property name=\"visible\">True</property>\n               "
  "                         <property name=\"sensitive\">False</property>\n"
  "                                        <property name=\"can_focus\">Tr"
  "ue</property>\n                                        <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                        <property name=\"adjustment\">adjustment4</prop"
  "erty>\n                                      </object>\n               "
  "                       <packing>\n                                     "
  "   <property name=\"expand\">False</property>\n                        "
  "                <property name=\"position\">1</property>\n             "
  "                         </packing>\n                                  "
  "  </child>\n                                  </object>\n              "
  "                    <packing>\n                                    <pro"
  "perty name=\"expand\">False</property>\n                               "
  "     <property name=\"position\">2</property>\n                        "
  "          </packing>\n                                </child>\n       "
  "                       </object>\n                            </child>\n"
  "                          </object>\n                        </child>\n"
  "                        <child type=\"label\">\n                       "
  "   <object class=\"GtkLabel\" id=\"label14\">\n                        "
  "    <property name=\"visible\">True</property>\n                       "
  "     <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MO"
  "TION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</prope"
  "rty>\n                            <property name=\"label\" translatable"
  "=\"yes\">&lt;b&gt;Appearance&lt;/b&gt;</property>\n                    "
  "        <property name=\"use_markup\">True</property>\n                "
  "          </object>\n                        </child>\n                "
  "      </object>\n                      <packing>\n                     "
  "   <property name=\"expand\">False</property>\n                      </"
  "packing>\n                    </child>\n                    <child>\n  "
  "                    <object class=\"GtkFrame\" id=\"frame7\">\n        "
  "                <property name=\"visible\">True</property>\n           "
  "             <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_PO"
  "INTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MAS"
  "K</property>\n                        <property name=\"label_xalign\">0"
  "</property>\n                        <property name=\"shadow_type\">GTK"
  "_SHADOW_NONE</property>\n                        <child>\n             "
  "             <object class=\"GtkAlignment\" id=\"alignment12\">\n      "
  "                      <property name=\"visible\">True</property>\n     "
  "                       <property name=\"events\">GDK_POINTER_MOTION_MAS"
  "K | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_R"
  "ELEASE_MASK</property>\n                            <property name=\"bo"
  "rder_width\">6</property>\n                            <property name=\""
  "left_padding\">6</property>\n                            <child>\n     "
  "                         <object class=\"GtkScrolledWindow\" id=\"scrol"
  "ledwindow2\">\n                                <property name=\"visible"
  "\">True</property>\n                                <property name=\"ca"
  "n_focus\">True</property>\n                                <property na"
  "me=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | "
  "GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n           "
  "                     <property name=\"hscrollbar_policy\">GTK_POLICY_AU"
  "TOMATIC</property>\n                                <property name=\"vs"
  "crollbar_policy\">GTK_POLICY_AUTOMATIC</property>\n                    "
  "            <property name=\"shadow_type\">GTK_SHADOW_ETCHED_IN</proper"
  "ty>\n                                <child>\n                         "
  "         <object class=\"GtkTreeView\" id=\"treeview_default_icons\">\n"
  "                                    <property name=\"visible\">True</pr"
  "operty>\n                                    <property name=\"can_focus"
  "\">True</property>\n                                    <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              "
  "                      <property name=\"headers_visible\">False</propert"
  "y>\n                                  </object>\n                      "
  "          </child>\n                              </object>\n          "
  "                  </child>\n                          </object>\n      "
  "                  </child>\n                        <child type=\"label"
  "\">\n                          <object class=\"GtkLabel\" id=\"label15\""
  ">\n                            <property name=\"visible\">True</propert"
  "y>\n                            <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                            <property "
  "name=\"label\" translatable=\"yes\">&lt;b&gt;Default Icons&lt;/b&gt;</p"
  "roperty>\n                            <property name=\"use_markup\">Tru"
  "e</property>\n                          </object>\n                    "
  "    </child>\n                      </object>\n                      <p"
  "acking>\n                        <property name=\"position\">1</propert"
  "y>\n                      </packing>\n                    </child>\n   "
  "               </object>\n                </child>\n                <ch"
  "ild type=\"tab\">\n                  <object class=\"GtkLabel\" id=\"la"
  "bel3\">\n                    <property name=\"visible\">True</property>"
  "\n                    <property name=\"events\">GDK_POINTER_MOTION_MASK"
  " | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RE"
  "LEASE_MASK</property>\n                    <property name=\"label\" tra"
  "nslatable=\"yes\">_Icons</property>\n                    <property name"
  "=\"use_underline\">True</property>\n                  </object>\n      "
  "            <packing>\n                    <property name=\"position\">"
  "2</property>\n                    <property name=\"tab_fill\">False</pr"
  "operty>\n                  </packing>\n                </child>\n      "
  "        </object>\n            </child>\n          </object>\n         "
  " <packing>\n            <property name=\"position\">1</property>\n     "
  "     </packing>\n        </child>\n        <child internal-child=\"acti"
  "on_area\">\n          <object class=\"GtkHButtonBox\" id=\"dialog-actio"
  "n_area1\">\n            <property name=\"visible\">True</property>\n   "
  "         <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTE"
  "R_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</p"
  "roperty>\n            <child>\n              <object class=\"GtkButton\""
  " id=\"button2\">\n                <property name=\"visible\">True</prop"
  "erty>\n                <property name=\"can_focus\">True</property>\n  "
  "              <property name=\"receives_default\">True</property>\n    "
  "            <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POI"
  "NTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK"
  "</property>\n                <property name=\"label\">gtk-help</propert"
  "y>\n                <property name=\"use_stock\">True</property>\n     "
  "         </object>\n            </child>\n            <child>\n        "
  "      <object class=\"GtkButton\" id=\"bnt_exit\">\n                <pr"
  "operty name=\"visible\">True</property>\n                <property name"
  "=\"can_focus\">True</property>\n                <property name=\"receiv"
  "es_default\">True</property>\n                <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <propert"
  "y name=\"label\">gtk-close</property>\n                <property name=\""
  "use_stock\">True</property>\n              </object>\n              <pa"
  "cking>\n                <property name=\"position\">1</property>\n     "
  "         </packing>\n            </child>\n          </object>\n       "
  "   <packing>\n            <property name=\"expand\">False</property>\n "
  "           <property name=\"pack_type\">GTK_PACK_END</property>\n      "
  "    </packing>\n        </child>\n      </object>\n    </child>\n    <a"
  "ction-widgets>\n      <action-widget response=\"-11\">button2</action-w"
  "idget>\n      <action-widget response=\"-3\">bnt_exit</action-widget>\n"
  "    </action-widgets>\n  </object>\n</interface>\n"
};

static const unsigned xfdesktop_settings_ui_length = 58939u;

